spring.application.name=backend
server.port=${PORT:8080}
spring.docker.compose.enabled=false
management.datadog.metrics.export.enabled=false
management.otlp.metrics.export.enabled=false

# --- Spring Security Default User ---
spring.security.user.name=super-admin@nestfy.com
spring.security.user.password=nestfy@3355


# --- Localhost Dev Defaults (docker-compose mapped ports) ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5433}/nestfy_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:nestfy_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:nestfy_s3cur3_p@ss!2026}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://nestfy_mongo_admin:m0ng0_s3cur3_pass_2026@localhost:27017/nestfy_nosql?authSource=admin}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6380}
spring.data.redis.password=${REDIS_PASSWORD:r3d1s_s3cur3_p@ss!2026}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}


